name = "QUT"
uuid = "a05c3b42-3203-472f-bab1-afcf4068e833"
authors = ["opentable fetcher <opentable-fetcher@git.nomics.world>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
